parameters:
#    zizoo_skipper.example.class: Zizoo\SkipperBundle\Example

services:
#    zizoo_skipper.example:
#        class: %zizoo_skipper.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
