
parameters:
    # Registration email
    zizoo_user.emails.contact_email: fetz4@gmx.net
    
    # Blogger max latest comments
    zizoo_user.confirm_registration:  false
    
    zizoo_user.facebook.app_id: 489344727785146
    
    zizoo_user.facebook.app_secret: 808d8b739582f34690c3b28858943cf2
    