# Registration
ZizooUserBundle_register:
  pattern:    /register
  defaults:   {_controller: ZizooUserBundle:Registration:register }  
  
ZizooUserBundle_submitted:
  pattern:    /submitted
  defaults:   {_controller: ZizooUserBundle:Registration:submitted }
  requirements:
        _method:  GET

ZizooUserBundle_confirm:
  pattern:    /confirm/{token}/email/{email}
  defaults:   {_controller: ZizooUserBundle:Registration:confirm }
  requirements:
        _method:  GET
        
ZizooUserBundle_change_email_confirm:
  pattern:    /change-email/{token}/email/{email}
  defaults:   {_controller: ZizooUserBundle:User:confirmChangeEmail }
  requirements:
        _method:  GET
        
ZizooUserBundle_confirmed:
  pattern:    /confirmed
  defaults:   {_controller: ZizooUserBundle:Registration:confirmed }
  requirements:
        _method:  GET|POST
        
ZizooUserBundle_resend_confirmation:
  pattern:    /resend-confirmation/email/{email}
  defaults:   {_controller: ZizooUserBundle:Registration:resendConfirmation }
  requirements:
        _method:  GET|POST
        
ZizooUserBundle_register_facebook:
  pattern:    /register-fb
  defaults:   {_controller: ZizooUserBundle:Registration:registerFacebook }
  
ZizooUserBundle_register_facebook_new:
  pattern:    /register-fb-new
  defaults:   {_controller: ZizooUserBundle:Registration:registerFacebookNew }
  
ZizooUserBundle_register_facebook_link:
  pattern:    /register-fb-link
  defaults:   {_controller: ZizooUserBundle:Registration:registerFacebookLink }

ZizooUserBundle_register_facebook_success:
  pattern:    /register-fb-success
  defaults:   {_controller: ZizooUserBundle:Registration:facebookSuccess }

ZizooUserBundle_register_facebook_merged:
  pattern:    /register-fb-merged
  defaults:   {_controller: ZizooUserBundle:Registration:facebookMerged }

ZizooUserBundle_login_facebook_fail:
  pattern:    /login-fb-fail
  defaults:   {_controller: ZizooUserBundle:User:facebookLoginFail }

# User
ZizooUserBundle_login:
    pattern:   /login
    defaults:  { _controller: ZizooUserBundle:User:login }
    
ZizooUserBundle_login_check:
    pattern:   /login_check
    
ZizooUserBundle_logout:
    pattern:   /logout

ZizooUserBundle_login_facebook:
     pattern: /login-fb
     defaults: {_controller: ZizooUserBundle:User:loginFacebook }
     
ZizooUserBundle_logout_facebook:
     pattern: /logout-fb
     defaults: {_controller: ZizooUserBundle:User:logoutFacebook }

ZizooUserBundle_forgot_password:
  pattern:    /forgot-password
  defaults:   {_controller: ZizooUserBundle:Registration:forgotPassword }
  defaults:   {_controller: ZizooUserBundle:User:forgotPassword }
  requirements:
        _method:  GET|POST
        
ZizooUserBundle_reset_password_email:
  pattern:    /reset-password
  defaults:   {_controller: ZizooUserBundle:Registration:resetPasswordEmail }
  defaults:   {_controller: ZizooUserBundle:User:resetPasswordEmail }
  requirements:
        _method:  GET|POST
        
ZizooUserBundle_reset_password:
  pattern:    /reset-password/{token}/email/{email}
  defaults:   {_controller: ZizooUserBundle:Registration:resetPassword }
  defaults:   {_controller: ZizooUserBundle:User:resetPassword }
  requirements:
        _method:  GET|POST
  
ZizooUserBundle_reset_password_confirm:
  pattern:    /reset-password-confirm/
  defaults:   {_controller: ZizooUserBundle:Registration:resetPasswordConfirm }
  defaults:   {_controller: ZizooUserBundle:User:resetPasswordConfirm }
  requirements:
        _method:  GET|POST

        _method:  GET|POST
        
ZizooUserBundle_invite:
  pattern:    /account/invite/
  defaults:   {_controller: ZizooUserBundle:User:inviteFriends }
  requirements:
        _method:  GET|POST 
        
ZizooUserBundle_forward:
  pattern:    /forward/{action}
  defaults:   {_controller: ZizooUserBundle:Registration:forward }
  
ZizooUserBundle_User_AccountSettings:
  pattern:    /account/settings/edit
  defaults:   {_controller: ZizooUserBundle:User:accountSettings }
  requirements:
        _method:  GET|POST 