# Registration
register:
  pattern:    /register
  defaults:   {_controller: ZizooUserBundle:Registration:register }  
  
submitted:
  pattern:    /submitted
  defaults:   {_controller: ZizooUserBundle:Registration:submitted }
  requirements:
        _method:  GET
confirm:
  pattern:    /confirm/{token}/email/{email}
  defaults:   {_controller: ZizooUserBundle:Registration:confirm }
  requirements:
        _method:  GET
        
confirmed:
  pattern:    /confirmed
  defaults:   {_controller: ZizooUserBundle:Registration:confirmed }
  requirements:
        _method:  GET|POST
        
resend_confirmation:
  pattern:    /resend-confirmation/email/{email}
  defaults:   {_controller: ZizooUserBundle:Registration:resendConfirmation }
  requirements:
        _method:  GET|POST
        
register_facebook:
  pattern:    /register-fb
  defaults:   {_controller: ZizooUserBundle:Registration:registerFacebook }
  
register_facebook_new:
  pattern:    /register-fb-new
  defaults:   {_controller: ZizooUserBundle:Registration:registerFacebookNew }
  
register_facebook_link:
  pattern:    /register-fb-link
  defaults:   {_controller: ZizooUserBundle:Registration:registerFacebookLink }

register_facebook_success:
  pattern:    /register-fb-success
  defaults:   {_controller: ZizooUserBundle:Registration:facebookSuccess }

register_facebook_merged:
  pattern:    /register-fb-merged
  defaults:   {_controller: ZizooUserBundle:Registration:facebookMerged }

login_facebook_fail:
  pattern:    /login-fb-fail
  defaults:   {_controller: ZizooUserBundle:User:facebookLoginFail }

# User
login:
    pattern:   /login
    defaults:  { _controller: ZizooUserBundle:User:login }
    
login_check:
    pattern:   /login_check
    
logout:
    pattern:   /logout

login_facebook:
     pattern: /login-fb
     defaults: {_controller: ZizooUserBundle:User:loginFacebook }
     
logout_facebook:
     pattern: /logout-fb
     defaults: {_controller: ZizooUserBundle:User:logoutFacebook }

forgot_password:
  pattern:    /forgot-password
  defaults:   {_controller: ZizooUserBundle:Registration:forgotPassword }
  defaults:   {_controller: ZizooUserBundle:User:forgotPassword }
  requirements:
        _method:  GET|POST
        
reset_password_email:
  pattern:    /reset-password
  defaults:   {_controller: ZizooUserBundle:Registration:resetPasswordEmail }
  defaults:   {_controller: ZizooUserBundle:User:resetPasswordEmail }
  requirements:
        _method:  GET|POST
        
reset_password:
  pattern:    /reset-password/{token}/email/{email}
  defaults:   {_controller: ZizooUserBundle:Registration:resetPassword }
  defaults:   {_controller: ZizooUserBundle:User:resetPassword }
  requirements:
        _method:  GET|POST
  
reset_password_confirm:
  pattern:    /reset-password-confirm/
  defaults:   {_controller: ZizooUserBundle:Registration:resetPasswordConfirm }
  defaults:   {_controller: ZizooUserBundle:User:resetPasswordConfirm }
  requirements:
        _method:  GET|POST

        _method:  GET|POST
        
change_password:
  pattern:    /account/change-password/
  defaults:   {_controller: ZizooUserBundle:User:changePassword }
  requirements:
        _method:  GET|POST 
        
invite:
  pattern:    /account/invite/
  defaults:   {_controller: ZizooUserBundle:User:inviteFriends }
  requirements:
        _method:  GET|POST 
        
forward:
  pattern:    /forward/{action}
  defaults:   {_controller: ZizooUserBundle:Registration:forward }