parameters:
#    zizoo_user.example.class: Zizoo\UserBundle\Example

services:
#    zizoo_user.example:
#        class: %zizoo_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
