services:
    # TWIG EXTENSIONS
    zizoo_user.twig.image_extension:
        class: Zizoo\UserBundle\Twig\UserExtension
        tags:
            - { name: twig.extension }
            
    facebook:
        class: Zizoo\UserBundle\Service\Facebook
        arguments: [{ appId: %zizoo_user.facebook.app_id%, secret: %zizoo_user.facebook.app_secret% }]
        
    zizoo_user_user_service:
        class:  Zizoo\UserBundle\Service\UserService
        arguments: 
            entityManager:  "@doctrine.orm.entity_manager"
            container:      "@service_container"
            
    zizoo_user.change_email_type:
        class:  Zizoo\UserBundle\Form\Type\UserNewEmailType
        tags:
            - { name: form.type, alias: zizoo_change_email }
            
    zizoo_user.invite_type:
        class:  Zizoo\UserBundle\Form\Type\InviteType
        tags:
            - { name: form.type, alias: zizoo_invite }
            
    zizoo_user.invite_single_type:
        class:  Zizoo\UserBundle\Form\Type\InviteSingleType
        tags:
            - { name: form.type, alias: zizoo_invite_single }
            
    # VALIDATORS
    zizoo_user.invite_single_validator:
        class: Zizoo\UserBundle\Validator\Constraints\InviteSingleValidator
        arguments: ["@service_container"]
        tags:
            - { name: validator.constraint_validator, alias: validator.invite_single_validator }
            