# src/Zizoo/UserBundle/Resources/config/validation.yml
Zizoo\UserBundle\Entity\User:
    properties:
        username:
            - NotBlank: { message: zizoo_user.error.username_not_blank, groups: [registration] }
            - MinLength: { limit: 5, message: zizoo_user.error.username_min_length, groups: [registration] }
            
        email:
            - NotBlank: { message: zizoo_user.error.email_not_blank, groups: [registration] }
            - Email:
                message: zizoo_user.error.email_email
                checkMX: true
                groups: [registration]
                
        password:
            - NotBlank: { message: zizoo_user.error.password_not_blank, groups: [registration, new_password] }
            - MinLength: { limit: 5, message: zizoo_user.error.password_min_length, groups: [registration, new_password] }
            
        newPassword:
            - NotBlank: { message: zizoo_user.error.password_not_blank, groups: [new_password] }
            - MinLength: { limit: 5, message: zizoo_user.error.password_min_length, groups: [new_password] }