# src/Zizoo/UserBundle/Resources/config/validation.yml
Zizoo\UserBundle\Entity\User:
    properties:
        username:
            - NotBlank: { message: zizoo_user.error.username_not_blank, groups: [registration, fb_link] }
            - MinLength: { limit: 5, message: zizoo_user.error.username_min_length, groups: [registration, fb_link] }
            
        email:
            - NotBlank: { message: zizoo_user.error.email_not_blank, groups: [registration, fb_link] }
            - Email:
                message: zizoo_user.error.email_email
                checkMX: true
                groups: [registration, fb_link]
                
        password:
            - NotBlank: { message: zizoo_user.error.password_not_blank, groups: [registration, fb_link] }
            - MinLength: { limit: 5, message: zizoo_user.error.password_min_length, groups: [registration, fb_link] }
    
Zizoo\UserBundle\Form\Model\UserNewPassword:
    properties:
        password:
            - NotBlank: { message: zizoo_user.error.new_password_not_blank, groups: [change_password] }
            - MinLength: { limit: 5, message: zizoo_user.error.password_min_length, groups: [change_password] }
            
Zizoo\UserBundle\Form\Model\UserNewEmail:
    properties:
        email:
            - NotBlank: { message: zizoo_user.error.new_email_not_blank, groups: [change_email] }
            - Email:
                message: zizoo_user.error.new_email_valid
                checkMX: true
                groups: [change_email]
            
Zizoo\UserBundle\Form\Model\Invitation:
    properties:
        email1:
          - Email:
              message: zizoo_user.error.email_email
              checkMX: true
              groups: [invitation]
        email2:
          - Email:
              message: zizoo_user.error.email_email
              checkMX: true
              groups: [invitation]
        email3:
          - Email:
              message: zizoo_user.error.email_email
              checkMX: true
              groups: [invitation]
        email4:
          - Email:
              message: zizoo_user.error.email_email
              checkMX: true
              groups: [invitation]
        email5:
          - Email:
              message: zizoo_user.error.email_email
              checkMX: true
              groups: [invitation]
              