<?php

namespace Zizoo\BookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
    
    public function getCharterBookings($charter)
    {
        $qb = $this->createQueryBuilder('booking')
                   ->leftJoin('booking.reservation', 'reservation')
                   ->leftJoin('reservation.boat', 'boat')
                   ->leftJoin('reservation.guest', 'guest')
                   ->leftJoin('boat.charter', 'charter')
                   ->select('booking')
                   ->where('charter = :charter')
                   ->setParameter('charter', $charter);

        return $qb->getQuery()
                  ->getResult();
    }
}
