<?php

namespace Zizoo\BookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
    
    public function getCharterBookings($charter, $status = null)
    {
        $qb = $this->createQueryBuilder('booking')
                   ->leftJoin('booking.reservation', 'reservation')
                   ->leftJoin('reservation.boat', 'boat')
                   ->leftJoin('reservation.guest', 'guest')
                   ->leftJoin('boat.charter', 'charter')
                   ->select('booking')
                   ->where('charter = :charter')
                        ->setParameter('charter', $charter);

        if ($status){
            $qb->andWhere('booking.status = :status')
                ->setParameter('status', $status);
        }

        return $qb->getQuery()
                  ->getResult();
    }

    public function getOutstandingBookings($charter)
    {
        return $this->getCharterBookings($charter, Booking::STATUS_OUTSTANDING);
    }

    public function getPaidBookings($charter)
    {
        return $this->getCharterBookings($charter, Booking::STATUS_PAID);
    }
    
    public function getUpcomingUserBookings($user, $limit=null)
    {
        $status = array(
            \Zizoo\ReservationBundle\Entity\Reservation::STATUS_ACCEPTED,
            \Zizoo\ReservationBundle\Entity\Reservation::STATUS_HOLD
        );
        $qb = $this->createQueryBuilder('booking')
                   ->leftJoin('booking.reservation', 'reservation')
                   ->leftJoin('reservation.boat', 'boat')
                   ->leftJoin('reservation.guest', 'guest')
                   ->leftJoin('boat.charter', 'charter')
                   ->select('booking')
                   ->where('guest = :guest')
                        ->setParameter('guest', $user)
                   ->andWhere('reservation.status IN (:status)')
                        ->setParameter('status', $status);

        $qb->orderBy('reservation.checkIn', 'ASC');
        
        if ($limit!==null){
            $qb->setFirstResult(0);
            $qb->setMaxResults($limit);
        }
        

        return $qb->getQuery()
                  ->getResult();
    }
}
