<?php

namespace Zizoo\BookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstalmentOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstalmentOptionRepository extends EntityRepository
{
}
