<?php

namespace Zizoo\BookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    
    public function getReservationBoatIds($resFrom, $resTo) {
        
        $qb = $this->createQueryBuilder('r')
                    ->select('r')
                    ->where('r.check_in BETWEEN :check_in AND :check_out')
                    ->orWhere('r.check_out BETWEEN :check_in AND :check_out')
                    ->orWhere(':check_in BETWEEN r.check_in AND r.check_out')
                    ->setParameter('check_in', $resFrom)
                    ->setParameter('check_out', $resTo);

        
        return $qb->getQuery()->getResult();
        
    }
    
}
