parameters:
#    admin_base.example.class: Admin\BaseBundle\Example

services:
#    admin_base.example:
#        class: %admin_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
