ZizooProfileBundle_Profile_Show:
    pattern:  /profile/{username}/show
    defaults: { _controller: ZizooProfileBundle:Profile:show }
    requirements:
        _method:  GET

ZizooProfileBundle_Profile_Edit:
    pattern:  /account/profile/edit
    defaults: { _controller: ZizooProfileBundle:Profile:edit }
    requirements:
        _method:  GET
        
ZizooProfileBundle_Profile_Edit_Widget:
    pattern:  /account/profile/{id}/edit_widget
    defaults: { _controller: ZizooProfileBundle:Profile:editWidget }
    requirements:
        _method:  GET
        
ZizooProfileBundle_Profile_Update:
    pattern:  /account/profile/{id}/{formPath}/update
    defaults: { _controller: ZizooProfileBundle:Profile:update }
    requirements:
      _method: POST
      id: \d+