ZizooProfileBundle_Profile_Show:
    pattern:  /profile/{username}/show
    defaults: { _controller: ZizooProfileBundle:Profile:show }
    requirements:
        _method:  GET

ZizooProfileBundle_Profile_Edit:
    pattern:  /account/profile/edit
    defaults: { _controller: ZizooProfileBundle:Profile:edit }
    requirements:
        _method:  GET|POST

ZizooProfileBundle_Profile_AddAvatar:
    pattern:  /account/profile/add-avatar
    defaults: { _controller: ZizooProfileBundle:Profile:addAvatar }
    requirements:
        _method:  POST
        
ZizooProfileBundle_Profile_GetAvatars:
    pattern:  /account/profile/avatars
    defaults: { _controller: ZizooProfileBundle:Profile:getAvatars }
    requirements:
        _method:  GET