parameters:
#    zizoo_profile.example.class: Zizoo\ProfileBundle\Example

services:
#    zizoo_profile.example:
#        class: %zizoo_profile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    profile_service:
        class:        Zizoo\ProfileBundle\Service\ProfileService
        arguments:
            entityManager:  "@doctrine.orm.entity_manager"
            container:      "@service_container"
  
    zizoo_profile.profile_type:
        class:  Zizoo\ProfileBundle\Form\Type\ProfileType
        arguments:
            container:      "@service_container"
        tags:
            - { name: form.type, alias: zizoo_profile }

    zizoo_profile.profile_subscriber:
        class: Zizoo\ProfileBundle\Form\EventListener\ProfileSubscriber
        arguments:
            container:      "@doctrine.orm.entity_manager"
        tags:
            - { name: form.event_listener, alias: 'zizoo_profile_listener' }
            
            
    # TWIG EXTENSIONS
    zizoo_profile.twig.profile_extension:
        class: Zizoo\ProfileBundle\Twig\ProfileExtension
        arguments:
            container:      "@service_container"
        tags:
            - { name: twig.extension }
 
