parameters:
#    zizoo_profile.example.class: Zizoo\ProfileBundle\Example

services:
#    zizoo_profile.example:
#        class: %zizoo_profile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
