parameters:
#    zizoo_profile.example.class: Zizoo\ProfileBundle\Example

services:
    profile_service:
        class:        Zizoo\ProfileBundle\Service\ProfileService
        arguments:
            entityManager:  "@doctrine.orm.entity_manager"