# src/Zizoo/ProfileBundle/Resources/config/validation.yml
Zizoo\ProfileBundle\Entity\Profile:
    properties:
        firstName:
            - NotBlank: { message: zizoo_user.error.first_name_not_blank, groups: [registration, default] }
            
        lastName:
            - NotBlank: { message: zizoo_user.error.last_name_not_blank, groups: [registration, default] }
            
        avatar:
            - Count:
                max: 2
                minMessage: "You must upload at least 1 profile avatar"
                maxMessage: "You cannot upload more than {{ limit }} avatars"
                groups: [default]
                
Zizoo\ProfileBundle\Entity\ProfileAvatar:
    properties:
        mimeType:
            - Regex:
                pattern: "/image\\/(png|jpeg)/"
                match:   true
                message: Only png and jpeg images are allowed
                groups: [default]