# src/Zizoo/ProfileBundle/Resources/config/validation.yml
Zizoo\ProfileBundle\Entity\Profile:
    properties:
        firstName:
            - NotBlank: { message: zizoo_user.error.first_name_not_blank, groups: [registration, Default] }
            
        lastName:
            - NotBlank: { message: zizoo_user.error.last_name_not_blank, groups: [registration, Default] }
            
        avatar:
            - Count:
                max: 3
                maxMessage: "You cannot upload more than {{ limit }} avatars"
                groups: [avatars]
            - Count:
                min: 1
                minMessage: "You must upload at least 1 avatar"
                groups: [Default]
                
                
Zizoo\AddressBundle\Entity\ProfileAddress:
    properties:
        addressLine1:
            - NotBlank: { message: zizoo_address.error.street_not_blank, groups: [Default] }

        postcode:
            - NotBlank: { message: zizoo_address.error.postcode_not_blank, groups: [Default] }
            
        locality:
            - NotBlank: { message: zizoo_address.error.locality_not_blank, groups: [Default] }
            
        country:
            - NotNull: { message: zizoo_address.error.country_not_null, groups: [Default] }
            

Zizoo\ProfileBundle\Entity\ProfileAvatar:
    properties:
        mimeType:
            - Regex:
                pattern: "/image\\/(png|jpeg)/"
                match:   true
                message: Only png and jpeg images are allowed
                groups: [avatars]