# src/Zizoo/ProfileBundle/Resources/config/validation.yml
Zizoo\ProfileBundle\Entity\Profile:
    properties:
        firstName:
            - NotBlank: { message: zizoo_user.error.first_name_not_blank, groups: [registration] }
            
        lastName:
            - NotBlank: { message: zizoo_user.error.last_name_not_blank, groups: [registration] }