ZizooBoatBundle_Boat_Show:
    pattern:  /boat/{id}/show
    defaults: { _controller: ZizooBoatBundle:Boat:show }
    requirements:
        _method:  GET|POST
        id: \d+

ZizooBoatBundle_Boat_New:
    pattern:  /charter/account/boat/new
    defaults: { _controller: ZizooBoatBundle:Boat:new }

ZizooBoatBundle_Boat_Create:
    pattern:  /charter/account/boat/create
    defaults: { _controller: ZizooBoatBundle:Boat:create }
    requirements: { _method: POST }

ZizooBoatBundle_Boat_Edit:
    pattern:  /charter/account/boat/{id}/edit
    defaults: { _controller: ZizooBoatBundle:Boat:edit }
    requirements:
        _method:  GET
        id: \d+

ZizooBoatBundle_Boat_EditDetails:
    pattern:  /charter/account/boat/{id}/edit/details
    defaults: { _controller: ZizooBoatBundle:Boat:editDetails }
    requirements:
        _method:  GET
        id: \d+

ZizooBoatBundle_Boat_EditPhotos:
    pattern:  /charter/account/boat/{id}/edit/photos
    defaults: { _controller: ZizooBoatBundle:Boat:editPhotos }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBoatBundle_Boat_AddPhoto:
    pattern:  /charter/account/boat/{id}/add-photo
    defaults: { _controller: ZizooBoatBundle:Boat:addPhoto }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBoatBundle_Boat_GetPhotos:
    pattern:  /charter/account/boat/{id}/photos
    defaults: { _controller: ZizooBoatBundle:Boat:getPhotos }
    requirements:
        _method:  GET|POST
        id: \d+

ZizooBoatBundle_Boat_EditPrice:
    pattern:  /charter/account/boat/{id}/edit/price
    defaults: { _controller: ZizooBoatBundle:Boat:editPrice }
    requirements:
        _method:  GET|POST
        id: \d+

ZizooBoatBundle_Boat_Active:
    pattern:  /charter/account/boat/active/{id}
    defaults: { _controller: ZizooBoatBundle:Boat:active, id: null }
    requirements:
        _method:  POST

ZizooBoatBundle_Boat_Upload:
    pattern:  /charter/account/boat/upload
    defaults: { _controller: ZizooBoatBundle:Boat:upload }


ZizooBoatBundle_Boat_Update:
    pattern:  /charter/account/boat/{id}/update
    defaults: { _controller: ZizooBoatBundle:Boat:update }
    requirements: 
        _method: POST
        id: \d+

ZizooBoatBundle_Boat_UpdateDetails:
    pattern:  /charter/account/boat/{id}/update/details
    defaults: { _controller: ZizooBoatBundle:Boat:updateDetails }
    requirements:
        _method: POST
        id: \d+

ZizooBoatBundle_Boat_Delete:
    pattern:  /charter/account/boat/{id}/delete
    defaults: { _controller: ZizooBoatBundle:Boat:delete }
    requirements: 
        _method: GET|POST 
        id: \d+
        
ZizooBoatBundle_booking_widget:
    pattern:  /booking_widget/{id}
    defaults: { _controller: ZizooBoatBundle:Boat:bookingWidget }
    requirements:
        _method:  GET|POST
        id: \d+