parameters:
    zizoo_boat.completeness_validation_groups: [boat_edit, boat_details, boat_photos]

services:
    # TWIG EXTENSIONS
    zizoo_boat.twig.image_extension:
        class: Zizoo\BoatBundle\Twig\ImageExtension
        tags:
            - { name: twig.extension }

    zizoo_boat.twig.boat_extension:
        class: Zizoo\BoatBundle\Twig\BoatExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
            
    zizoo_boat.twig.availability_extension:
        class: Zizoo\BoatBundle\Twig\AvailabilityExtension
        tags:
            - { name: twig.extension }


    # SERVICES
    boat_service:
        class:  Zizoo\BoatBundle\Service\BoatService
        arguments: 
            entityManager:  "@doctrine.orm.entity_manager"
            messenger:      "@messenger"
            container:      "@service_container"
    
    
    # DATA TRANSFORMERS
    zizoo_boat.boat_type_data_transformer:
        class:  Zizoo\BoatBundle\Form\DataTransformer\BoatTypeTransformer
        arguments: ["@doctrine.orm.entity_manager"]
    
    
    # FORM TYPES
    zizoo_boat.boat_type_selector:
        class:  Zizoo\BoatBundle\Form\Type\BoatTypeType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: zizoo_boat_type_selector }
            
    zizoo_boat.equipment_selector:
        class:  Zizoo\BoatBundle\Form\Type\EquipmentType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: zizoo_equipment_selector }
            
    zizoo_boat.book_boat_type:
        class:  Zizoo\BoatBundle\Form\Type\BookBoatType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: zizoo_boat_book }

    zizoo_boat.boat_image_type:
            class:  Zizoo\BoatBundle\Form\Type\BoatImageType
            tags:
                - { name: form.type, alias: zizoo_boat_image }
                
    zizoo_boat.boat_availability_type:
            class:  Zizoo\BoatBundle\Form\Type\AvailabilityType
            arguments: ["@service_container"]
            tags:
                - { name: form.type, alias: zizoo_boat_availability }
            
            
    # FORM EXTENSIONS
    zizoo_boat.book_boat_type_extension:
        class:  Zizoo\BoatBundle\Form\Extension\BookBoatTypeExtension
        tags:
            - { name: form.type_extension, alias: zizoo_boat_book }
            
    zizoo_boat.boat_image_type_extension:
            class:  Zizoo\BoatBundle\Form\Extension\BoatImageType
            tags:
                - { name: form.type_extension, alias: zizoo_boat_image }
                
    zizoo_boat.boat_availability_type_extension:
            class:  Zizoo\BoatBundle\Form\Extension\AvailabilityTypeExtension
            tags:
                - { name: form.type_extension, alias: zizoo_boat_availability }
            
            
    # VALIDATORS
    zizoo_boat.book_boat_validator:
        class: Zizoo\BoatBundle\Validator\Constraints\BookBoatValidator
        arguments: ["@service_container"]
        tags:
            - { name: validator.constraint_validator, alias: validator.book_boat_validator }
            
    zizoo_boat.boat_validator:
        class: Zizoo\BoatBundle\Validator\Constraints\BoatValidator
        tags:
            - { name: validator.constraint_validator, alias: validator.boat_validator }
            
    zizoo_boat.availability_validator:
        class: Zizoo\BoatBundle\Validator\Constraints\AvailabilityValidator
        tags:
            - { name: validator.constraint_validator, alias: validator.availability_validator }

   # LISTENERS
    zizoo_boat_boat_listener:
        class: Zizoo\BoatBundle\EventListener\BoatListener
        arguments:
            container:      "@service_container"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            
    zizoo_boat_price_listener:
        class: Zizoo\BoatBundle\EventListener\PriceListener
        arguments:
            container:      "@service_container"
        tags:
            - { name: doctrine.event_listener, event: onFlush }
