parameters:
#    zizoo_boat.example.class: Zizoo\BoatBundle\Example

services:
    zizoo_boat.twig.image_extension:
        class: Zizoo\BoatBundle\Twig\ImageExtension
        tags:
            - { name: twig.extension }

    zizoo_boat.twig.boat_extension:
        class: Zizoo\BoatBundle\Twig\BoatExtension
        tags:
            - { name: twig.extension }
            
    boat_service:
        class:  Zizoo\BoatBundle\Service\BoatService
        arguments: 
            entityManager:  "@doctrine.orm.entity_manager"
            messenger:      "@messenger"
            container:      "@service_container"
    
    zizoo_boat.boat_type_data_transformer:
        class:  Zizoo\BoatBundle\Form\DataTransformer\BoatTypeTransformer
        arguments: ["@doctrine.orm.entity_manager"]
    
    zizoo_boat.boat_type_selector:
        class:  Zizoo\BoatBundle\Form\Type\BoatTypeType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: zizoo_boat_type_selector }
#    zizoo_boat.example:
#        class: %zizoo_boat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
