Zizoo\BoatBundle\Form\Model\BookBoat:
    constraints:
        - Zizoo\BoatBundle\Validator\Constraints\BookBoat: ~
        
Zizoo\BoatBundle\Form\Model\Availability:
    constraints:
        - Zizoo\BoatBundle\Validator\Constraints\Availability: ~
    
    properties:
        confirm:
            - "True": { message: "Please confirm." }
           
Zizoo\BoatBundle\Form\Model\ReservationRange:
    properties:
        reservation_from:
            - Date: ~
            - NotNull: ~
            
        reservation_to:
            - Date: ~
            - NotNull: ~

Zizoo\BoatBundle\Entity\Boat:
    constraints:
        - Zizoo\BoatBundle\Validator\Constraints\Boat:
            groups: [boat_edit, boat_complete]
        
    properties:
        # Boat edit
        name:
            - NotBlank:
                message: Name must not be blank
                groups: [boat_edit, boat_complete]
                                
        brand:
            - NotBlank:
                message: Brand must not be blank
                groups: [boat_edit, boat_complete]
                
        model:
            - NotBlank:
                message: Model must not be blank
                groups: [boat_edit, boat_complete]
                
        length:
            - Range:
                min: 0
                max: 4294967295
                minMessage: Your boat is too small
                maxMessage: Your boat is too big
                groups: [boat_edit, boat_complete]
                
            - NotBlank:
                message: Length must not be blank
                groups: [boat_edit, boat_complete]
                
        cabins:
            - Range:
                min: 0
                max: 4294967295
                minMessage: Your boat doesn't have enough cabins
                maxMessage: Your boat has too many cabins
                groups: [boat_edit, boat_complete]
                
            - NotBlank:
                message: Cabins must not be blank
                groups: [boat_edit, boat_complete]
                
        berths:
            - Range:
                min: 0
                max: 4294967295
                minMessage: Your boat doesn't have enough berths
                maxMessage: Your boat has too many berths
                groups: [boat_edit, boat_complete]
                
            - NotBlank:
                message: Berths must not be blank
                groups: [boat_edit, boat_complete]
                
        bathrooms:
            - Range:
                min: 0
                max: 4294967295
                minMessage: Your boat doesn't have enough bathrooms
                maxMessage: Your boat has too many bathrooms
                groups: [boat_edit, boat_complete]
                
            - NotBlank:
                message: Bathrooms must not be blank
                groups: [boat_edit, boat_complete]
              
        toilets:
            - Range:
                min: 0
                max: 4294967295
                minMessage: Your boat doesn't have enough toilets
                maxMessage: Your boat has too many toilets
                groups: [boat_edit, boat_complete]
                
            - NotBlank:
                message: Toilets must not be blank
                groups: [boat_edit, boat_complete]
                
        nr_guests:
            - Range:
                min: 0
                max: 4294967295
                minMessage: Your boat can't handle enough guests
                maxMessage: Your boat attempts to handle too many guests
                groups: [boat_edit, boat_complete]
                
            - NotBlank:
                message: Number of guests must not be blank
                groups: [boat_edit, boat_complete]
                
                
        # Boat details 
        description:
            - NotBlank:
                message: Description must not be blank
                groups: [boat_details, boat_complete]
        
        title:
            - NotBlank:
                message: Title must not be blank
                groups: [boat_details, boat_complete]
                
                
        # Boat images
        image:
            - Count:
                max: 10
                maxMessage: "You cannot upload more than {{ limit }} images"
                groups: [boat_photos]
                
            - Count:
                min: 1
                minMessage: "You must upload at least 1 boat image"
                groups: [boat_complete]
                
        

Zizoo\BoatBundle\Entity\BoatImage:
    properties:
        mimeType:
            - Regex:
                pattern: "/image\\/(png|jpeg)/"
                match:   true
                message: Only png and jpeg images are allowed
                groups: [boat_photos]
                
                
Zizoo\AddressBundle\Entity\BoatAddress:
    properties:
        addressLine1:
            - NotBlank: { message: zizoo_address.error.street_not_blank, groups: [boat_edit] }

        postcode:
            - NotBlank: { message: zizoo_address.error.postcode_not_blank, groups: [boat_edit] }
            
        locality:
            - NotBlank: { message: zizoo_address.error.locality_not_blank, groups: [boat_edit] }
            
        country:
            - NotNull: { message: zizoo_address.error.country_not_null, groups: [boat_edit] }