Zizoo\BoatBundle\Form\Model\BookBoat:
    constraints:
        - Zizoo\BoatBundle\Validator\Constraints\BookBoat: ~

Zizoo\BoatBundle\Entity\Boat:
    properties:
        # Boat edit
        name:
            - NotBlank:
                message: Name must not be blank
                groups: [boat_edit]
                                
        brand:
            - NotBlank:
                message: Brand must not be blank
                groups: [boat_edit]
                
        model:
            - NotBlank:
                message: Model must not be blank
                groups: [boat_edit]
                
        length:
            - NotBlank:
                message: Length must not be blank
                groups: [boat_edit]
                
        cabins:
            - NotBlank:
                message: Cabins must not be blank
                groups: [boat_edit]
                
        berths:
            - NotBlank:
                message: Berths must not be blank
                groups: [boat_edit]
                
        bathrooms:
          - NotBlank:
              message: Bathrooms must not be blank
              groups: [boat_edit]
              
        toilets:
            - NotBlank:
                message: Toilets must not be blank
                groups: [boat_edit]
                
        nr_guests:
            - NotBlank:
                message: Number of guests must not be blank
                groups: [boat_edit]
                
                
        # Boat details 
        description:
            - NotBlank:
                message: Description must not be blank
                groups: [boat_details]
        
        title:
            - NotBlank:
                message: Title must not be blank
                groups: [boat_details]
                
                
        # Boat images
        image:
            - Count:
                min: 1
                max: 10
                minMessage: "You must upload at least 1 boat image"
                maxMessage: "You cannot upload more than {{ limit }} images"
                groups: [boat_photos]
                
        

Zizoo\BoatBundle\Entity\BoatImage:
    properties:
        mimeType:
            - Regex:
                pattern: "/image\\/(png|jpeg)/"
                match:   true
                message: Only png and jpeg images are allowed
                groups: [boat_photos]
                
                
Zizoo\AddressBundle\Entity\BoatAddress:
    properties:
        addressLine1:
            - NotBlank: { message: zizoo_address.error.street_not_blank, groups: [boat_edit] }

        postcode:
            - NotBlank: { message: zizoo_address.error.postcode_not_blank, groups: [boat_edit] }
            
        locality:
            - NotBlank: { message: zizoo_address.error.locality_not_blank, groups: [boat_edit] }
            
        country:
            - NotNull: { message: zizoo_address.error.country_not_null, groups: [boat_edit] }