imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            #- form_table_layout.html.twig
            
            - ZizooAddressBundle:Form:Div/fields.html.twig
            - ZizooBoatBundle:Form:Div/fields.html.twig
            - ZizooBookingBundle:Form:Div/fields.html.twig
            - ZizooMediaBundle:Form:Div/fields.html.twig
            - ZizooUserBundle:Form:Div/fields.html.twig
            - ZizooCrewBundle:Form:Div/fields.html.twig
            - ZizooBaseBundle:Form:Div/fields.html.twig
            

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
            
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"        
        entity_managers:
            default:
                auto_mapping: true
                hydrators:
                    user_profile_hydrator:    Zizoo\MessageBundle\Extensions\Hydrators\UserProfileHydrator
                dql:
                    string_functions:
                        group_concat: Zizoo\MessageBundle\Extensions\DoctrineExtensions\Query\Mysql\GroupConcat
        
                    

liip_imagine:
    filter_sets:
        thumb_50x50:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound, allow_upscale: true }
                
        thumb_120x80:
            quality: 75
            filters:
                thumbnail: { size: [120, 80], mode: outbound, allow_upscale: true }
            
        thumb_131x68:
            quality: 75
            filters:
                thumbnail: { size: [131, 68], mode: outbound, allow_upscale: true }
                
        thumb_218x114:
            quality: 75
            filters:
                thumbnail: { size: [218, 114], mode: outbound, allow_upscale: true }
                
        thumb_190x_:
            quality: 75
            filters:
                relative_resize: { widen: 190 }
                
                
                
zizoo_jq_grid_custom: 
    datepicker_format: dd/mm/yy
    datepickerphp_format: d/m/Y
    
    
fos_message:
    db_driver: orm
    thread_class: Zizoo\MessageBundle\Entity\Thread
    message_class: Zizoo\MessageBundle\Entity\Message
    new_thread_form:
        #type:   zizoo_message.new_thread_form.type
        type:               zizoo_message.new_thread_multiple_form_type
        handler:            zizoo_message.new_thread_multiple_form.handler
        model:              Zizoo\MessageBundle\Form\Model\NewThreadMultipleMessage
    reply_form:
        #type:   zizoo_message.new_thread_form.type
        type:               zizoo_message.reply_form_type
        handler:            zizoo_message.reply_form.handler
        model:              Zizoo\MessageBundle\Form\Model\ReplyMessage

jms_payment_core:
    secret: someS3cretP4ssw0rd

zizoo_base:
    dashboard_routes:
        user_routes:  
            profile_route:              ZizooBaseBundle_Dashboard_Profile
            skills_route:               ZizooBaseBundle_Dashboard_Skills
            bookings_route:             ZizooBaseBundle_Dashboard_Trips
            view_booking_route:         ZizooBaseBundle_Dashboard_ViewTrip
            inbox_route:                ZizooBaseBundle_Dashboard_Inbox
            view_thread_route:          ZizooBaseBundle_Dashboard_ViewThread
            account_settings_route:     ZizooBaseBundle_Dashboard_AccountSettings
            verify_facebook_route:      ZizooBaseBundle_Dashboard_VerifyFacebook
            unverify_facebook_route:    ZizooBaseBundle_Dashboard_UnverifyFacebook
            verify_phone_route:         ZizooBaseBundle_Dashboard_VerifyPhone
            verify_send_route:          ZizooBaseBundle_Dashboard_VerifySend

        charter_routes:  
            profile_route:              ZizooBaseBundle_Dashboard_CharterProfile
            bookings_route:             ZizooBaseBundle_Dashboard_CharterBookings
            view_booking_route:         ZizooBaseBundle_Dashboard_CharterViewBooking
            accept_booking_route:       ZizooBaseBundle_Dashboard_CharterAcceptBooking
            deny_booking_route:         ZizooBaseBundle_Dashboard_CharterDenyBooking
            inbox_route:                ZizooBaseBundle_Dashboard_CharterInbox
            view_thread_route:          ZizooBaseBundle_Dashboard_CharterViewThread
            payments_route:             ZizooBaseBundle_Dashboard_CharterPayments
            payout_settings_route:      ZizooBaseBundle_Dashboard_CharterPayoutSettings
            boats_route:                ZizooBaseBundle_Dashboard_CharterBoats
            boat_new_route:             ZizooBaseBundle_Dashboard_CharterNewBoat
            boat_edit_route:            ZizooBaseBundle_Dashboard_CharterEditBoat
            boat_details_route:         ZizooBaseBundle_Dashboard_CharterEditDetailsBoat
            boat_photos_route:          ZizooBaseBundle_Dashboard_CharterEditPhotosBoat
            boat_calendar_route:        ZizooBaseBundle_Dashboard_CharterEditPriceBoat
            boat_delete_route:          ZizooBaseBundle_Dashboard_CharterDeleteBoat
            boat_active_route:          ZizooBaseBundle_Dashboard_CharterActiveBoat

#knp_paginator:
#    template:
#        pagination: ZizooBaseBundle:Elements:pagination_sliding.html.twig
