imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - ZizooBookingBundle:Form:fields.html.twig
            - ZizooUserBundle:Form:fields.html.twig
            - ZizooBoatBundle:Form:fields.html.twig
            - ZizooAddressBundle:Form:fields.html.twig
            - ZizooMediaBundle:Form:fields.html.twig

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
            
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"        
        entity_managers:
            default:
                auto_mapping: true
                hydrators:
                    user_profile_hydrator:    Zizoo\MessageBundle\Extensions\Hydrators\UserProfileHydrator
                dql:
                    string_functions:
                        group_concat: Zizoo\MessageBundle\Extensions\DoctrineExtensions\Query\Mysql\GroupConcat
        
                    

liip_imagine:
    filter_sets:
        thumb_50x50:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound, allow_upscale: true }
        thumb_75x75:
            quality: 75
            filters:
                thumbnail: { size: [75, 75], mode: outbound, allow_upscale: true }
        thumb_120x80:
            quality: 75
            filters:
                thumbnail: { size: [120, 80], mode: outbound, allow_upscale: true }
        zizoo_thumb_120x80:
            quality: 90
            filters:
                crop_and_thumbnail: { size: [120, 80], mode: outbound, allow_upscale: true }
                
                
                
zizoo_jq_grid_custom: 
    datepicker_format: dd/mm/yy
    datepickerphp_format: d/m/Y
    
    
fos_message:
    db_driver: orm
    thread_class: Zizoo\MessageBundle\Entity\Thread
    message_class: Zizoo\MessageBundle\Entity\Message
    new_thread_form:
        #type:   zizoo_message.new_thread_form.type
        type:               zizoo_message.new_thread_multiple_form_type
        handler:            zizoo_message.new_thread_multiple_form.handler
        model:              Zizoo\MessageBundle\Form\Model\NewThreadMultipleMessage
    reply_form:
        #type:   zizoo_message.new_thread_form.type
        type:               zizoo_message.reply_form_type
        handler:            zizoo_message.reply_form.handler
        model:              Zizoo\MessageBundle\Form\Model\ReplyMessage