imports:
    - { resource: parameters_local.yml }

parameters:
    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            YGREfaHmfclAfUpSlwRTL0sWAUQJxMrfcJ9XpbHjHWIx6ry2ZlC4lwNMBLL5GBKp
    remember_me_secret: fuckadoodledoo

    file_uploader.allowed_extensions:
    # Mime types are just for documentation's sake. 
    # BlueImp filters by supplied extension. No checking of the
    # actual file contents is done. If your mime types are 
    # configured correctly in Apache the browser will have the
    # correct expectations for each file
    - gif #image/gif
    - png #image/png
    - jpg #image/jpeg
    - jpeg #image/jpeg
    
    file_uploader.sizes: ~