zizoo_mango_pay:
    resource: "@ZizooMangoPayBundle/Resources/config/routing.yml"
    prefix:   /

Zizoo_Routing:
    resource: "routing-zizoo.yml"
    prefix:   /

Admin_Routing:
    resource: "routing-admin.yml"
    prefix:   /