parameters:
#    zizoo_notification.example.class: Zizoo\NotificationBundle\Example

services:
#    zizoo_notification.example:
#        class: %zizoo_notification.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
