ZizooBookingBundle_book:
    pattern: /book/
    defaults: { _controller: ZizooBookingBundle:Booking:book }
    requirements:
        _method:  GET|POST
                
ZizooBookingBundle_view_booking:
    pattern: /booking/{id}
    defaults: { _controller: ZizooBookingBundle:Booking:viewBooking }
    requirements:
        _method:  GET
        
ZizooBookingBundle_view_all_bookings:
    pattern: /bookings
    defaults: { _controller: ZizooBookingBundle:Booking:viewAllBookings }
    requirements:
        _method:  GET