parameters:
#    zizoo_booking.example.class: Zizoo\BookingBundle\Example

services:
    booking_agent:
        class:  Zizoo\BookingBundle\Service\BookingAgent
        arguments: 
            entityManager:  "@doctrine.orm.entity_manager"
            messenger:      "@messenger"
            container:      "@service_container"
#    zizoo_booking.example:
#        class: %zizoo_booking.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
