parameters:
    zizoo_booking.cut_amount: 0.12
    zizoo_booking.allow_bookings: true
#    zizoo_booking.example.class: Zizoo\BookingBundle\Example

services:
    zizoo_booking_booking_agent:
        class:  Zizoo\BookingBundle\Service\BookingAgentController
        arguments: 
            entityManager:  "@doctrine.orm.entity_manager"
            messenger:      "@messenger"
            container:      "@service_container"
            
    zizoo_booking.twig.book_boat_extension:
        class: Zizoo\BookingBundle\Twig\BookBoatExtension
        arguments:
            container:      "@service_container"
        tags:
            - { name: twig.extension }
            
    zizoo_booking.twig.booking_extension:
        class: Zizoo\BookingBundle\Twig\BookingExtension
        arguments:
            bookingAent:    "@zizoo_booking_booking_agent"
        tags:
            - { name: twig.extension }
            
    zizoo_booking.twig.payment_extension:
        class: Zizoo\BookingBundle\Twig\PaymentExtension
        arguments:
            container:      "@service_container"
        tags:
            - { name: twig.extension }
            
    zizoo_booking.booking_type:
        class:  Zizoo\BookingBundle\Form\Type\BookingType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: zizoo_booking_type }
#    zizoo_booking.example:
#        class: %zizoo_booking.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
