parameters:
#    zizoo_booking.example.class: Zizoo\BookingBundle\Example

services:
#    zizoo_booking.example:
#        class: %zizoo_booking.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
