ZizooMessageBundle_delete_thread:
    pattern: /delete-thread/{messageId}
    defaults: { _controller: ZizooMessageBundle:Message:deleteForm, messageId: null, ajax: false}
    
ZizooMessageBundle_mark_thread:
    pattern: /mark-message/{threadId}/{read}
    defaults: { _controller: ZizooMessageBundle:Message:markRead, threadId: null, read: true}
   
ZizooMessageBundle_thread_view:
    pattern: /view/{threadId}
    defaults: { _controller: FOSMessageBundle:Message:thread, threadId: null, ajax: false }
   
ZizooMessageBundle_new_thread:
    pattern: /test
    defaults: { _controller: ZizooMessageBundle:Message:newThread }
    
ZizooMessageBundle_Message_Inbox:
    pattern: /view
    defaults: { _controller: ZizooMessageBundle:Message:inbox }
    
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /