inbox:
    pattern:  /inbox
    defaults: { _controller: ZizooMessageBundle:Message:inbox }

inbox_data:
    pattern:  /inbox-data
    defaults: { _controller: ZizooMessageBundle:Message:inboxData }
    
sent:
    pattern:  /sent
    defaults: { _controller: ZizooMessageBundle:Message:sent }