parameters:
#    zizoo_message.example.class: Zizoo\MessageBundle\Example

services:
    messenger:
        class:  Zizoo\MessageBundle\Service\Messenger
        arguments: 
            entityManager:  "@doctrine.orm.entity_manager"
            container:      "@service_container"
            
    zizoo_profile.twig.profile_extension:
        class: Zizoo\ProfileBundle\Twig\ProfileExtension
        tags:
            - { name: twig.extension }
            
#    zizoo_message.example:
#        class: %zizoo_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
