parameters:
#    zizoo_message.example.class: Zizoo\MessageBundle\Example

services:
#    zizoo_message.example:
#        class: %zizoo_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
