ZizooBaseBundle_homepage:
    pattern:  /
    defaults: { _controller: ZizooBaseBundle:Page:index }
    requirements:
        _method:  GET
        
ZizooBaseBundle_how:
    pattern:  /how
    defaults: { _controller: ZizooBaseBundle:Page:how }
    requirements:
        _method:  GET
        
ZizooBaseBundle_about:
    pattern:  /about
    defaults: { _controller: ZizooBaseBundle:Page:about }
    requirements:
        _method:  GET
        
ZizooBaseBundle_terms:
    pattern:  /terms
    defaults: { _controller: ZizooBaseBundle:Page:terms }
    requirements:
        _method:  GET
        
ZizooBaseBundle_policies:
    pattern:  /policies
    defaults: { _controller: ZizooBaseBundle:Page:policies }
    requirements:
        _method:  GET
        
ZizooBaseBundle_feedback:
    pattern:  /feedback
    defaults: { _controller: ZizooBaseBundle:Page:feedback }
    requirements:
        _method:  GET|POST
        
ZizooBaseBundle_faq:
    pattern:  /faq
    defaults: { _controller: ZizooBaseBundle:Page:faq }
    requirements:
        _method:  GET
        
ZizooBaseBundle_login_page:
    pattern:  /login-page
    defaults: { _controller: ZizooBaseBundle:Page:login }
    requirements:
        _method:  GET|POST
        
ZizooBaseBundle_login_widget:
    pattern:  /login-widget
    defaults: { _controller: ZizooBaseBundle:Page:loginWidget }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard:
    pattern:  /charter/account/dashboard
    defaults: { _controller: ZizooBaseBundle:Dashboard:index }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_CharterDashboard:
    pattern:  /charter/account/dashboard
    defaults: { _controller: ZizooBaseBundle:Dashboard:index }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_UserDashboard:
    pattern:  /account/dashboard
    defaults: { _controller: ZizooBaseBundle:Dashboard:index }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_Widget:
    pattern:  /dashboard-widget
    defaults: { _controller: ZizooBaseBundle:Dashboard:widget }
    requirements:
        _method:  GET

ZizooBaseBundle_Dashboard_Profile:
    pattern:  /account/profile
    defaults: { _controller: ZizooBaseBundle:Dashboard:profile }
    requirements:
        _method:  GET|POST

ZizooBaseBundle_Dashboard_Skills:
    pattern:  /account/skills
    defaults: { _controller: ZizooBaseBundle:Dashboard:skills }
    requirements:
        _method:  GET

ZizooBaseBundle_Dashboard_Trips:
    pattern:  /account/trips
    defaults: { _controller: ZizooBaseBundle:Dashboard:trips }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_Inbox:
    pattern:  /account/inbox
    defaults: { _controller: ZizooBaseBundle:Dashboard:inbox }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_CharterProfile:
    pattern:  /charter/account/profile
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterProfile }
    requirements:
        _method:  GET|POST    
        
ZizooBaseBundle_Dashboard_CharterInbox:
    pattern:  /charter/account/inbox
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterInbox }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_CharterSent:
    pattern:  /charter/account/sent
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterSent }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_CharterBookings:
    pattern:  /charter/account/bookings
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBookings }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_CharterBoats:
    pattern:  /charter/account/boats/{listing_status}
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoats, listing_status: all }
    requirements:
        _method:  GET
        listing_status:  active|incomplete|hidden|all
                
ZizooBaseBundle_Dashboard_CharterPayments:
    pattern:  /charter/account/payments
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterPayments }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_CharterPayoutSettings:
    pattern:  /charter/account/payout-settings
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterPayoutSettings }
    requirements:
        _method:  GET|POST