ZizooBaseBundle_homepage:
    pattern:  /
    defaults: { _controller: ZizooBaseBundle:Page:index }
    requirements:
        _method:  GET
        
ZizooBaseBundle_how:
    pattern:  /how/{what}
    defaults: { _controller: ZizooBaseBundle:Page:how, what: 'charter' }
    requirements:
        _method:  GET
        what: charter|holidayer|skipper
        
ZizooBaseBundle_about:
    pattern:  /about
    defaults: { _controller: ZizooBaseBundle:Page:about }
    requirements:
        _method:  GET
        
ZizooBaseBundle_terms:
    pattern:  /terms
    defaults: { _controller: ZizooBaseBundle:Page:terms }
    requirements:
        _method:  GET
        
ZizooBaseBundle_policies:
    pattern:  /policies
    defaults: { _controller: ZizooBaseBundle:Page:policies }
    requirements:
        _method:  GET
        
ZizooBaseBundle_feedback:
    pattern:  /feedback
    defaults: { _controller: ZizooBaseBundle:Page:feedback }
    requirements:
        _method:  GET|POST
        
ZizooBaseBundle_faq:
    pattern:  /faq
    defaults: { _controller: ZizooBaseBundle:Page:faq }
    requirements:
        _method:  GET
        
ZizooBaseBundle_login_page:
    pattern:  /login-page
    defaults: { _controller: ZizooBaseBundle:Page:login }
    requirements:
        _method:  GET|POST
        
ZizooBaseBundle_login_widget:
    pattern:  /login-widget
    defaults: { _controller: ZizooBaseBundle:Page:loginWidget }
    requirements:
        _method:  GET
                
                        
# USER                       
ZizooBaseBundle_Dashboard_UserDashboard:
    pattern:  /account/dashboard
    defaults: { _controller: ZizooBaseBundle:Dashboard:indexUser }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_Widget:
    pattern:  /dashboard-widget
    defaults: { _controller: ZizooBaseBundle:Dashboard:widget }
    requirements:
        _method:  GET

# USER (shared dashboard action)
ZizooBaseBundle_Dashboard_Profile:
    pattern:  /account/dashboard/profile
    defaults: { _controller: ZizooBaseBundle:Dashboard:user, other_controller: ZizooProfileBundle:Profile:edit, title: 'My Profile', tab: profile }
    requirements:
        _method:  GET|POST

ZizooBaseBundle_Dashboard_Skills:
    pattern:  /account/dashboard/skills
    defaults: { _controller: ZizooBaseBundle:Dashboard:user, other_controller: ZizooCrewBundle:Skills:add, title: 'My Skills', tab: skills }
    requirements:
        _method:  GET

ZizooBaseBundle_Dashboard_Trips:
    pattern:  /account/dashboard/trips
    defaults: { _controller: ZizooBaseBundle:Dashboard:user, other_controller: ZizooBookingBundle:Booking:viewAllBookings, title: 'My Trips', tab: bookings }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_ViewTrip:
    pattern:  /account/dashboard/trips/{id}
    defaults: { _controller: ZizooBaseBundle:Dashboard:user, other_controller: ZizooBookingBundle:Booking:viewBooking, tab: bookings }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_Inbox:
    pattern:  /account/dashboard/inbox
    defaults: { _controller: ZizooBaseBundle:Dashboard:user, other_controller: ZizooMessageBundle:Message:inbox, title: 'My Inbox', tab: inbox }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_ViewThread:
    pattern:  /account/dashboard/inbox/{threadId}
    defaults: { _controller: ZizooBaseBundle:Dashboard:user, other_controller: FOSMessageBundle:Message:thread, view: 'user', tab: inbox }
    requirements:
        _method:  GET|POST
        threadId: \d+
        
ZizooBaseBundle_Dashboard_AccountSettings:
    pattern:  /account/dashboard/settings
    defaults: { _controller: ZizooBaseBundle:Dashboard:user, other_controller: ZizooUserBundle:User:accountSettings, title: 'Account Settings', tab: account }
    requirements:
        _method:  GET|POST
   
ZizooBaseBundle_Dashboard_VerifyFacebook:
    pattern:  /account/dashboard/verify-facebook
    defaults: { _controller: ZizooBaseBundle:Dashboard:user, other_controller: ZizooUserBundle:Verification:verifyFacebook, title: 'Verify Facebook' }
    requirements:
        _method:  GET|POST
        
        
ZizooBaseBundle_Dashboard_UnverifyFacebook:
    pattern:  /account/dashboard/unverify-facebook
    defaults: { _controller: ZizooBaseBundle:Dashboard:user, other_controller: ZizooUserBundle:Verification:unverifyFacebook, title: 'Unverify Facebook' }
    requirements:
        _method:  GET|POST

ZizooBaseBundle_Dashboard_VerifyPhone:
    pattern:  /account/dashboard/verify-phone
    defaults: { _controller: ZizooBaseBundle:Dashboard:user, other_controller: ZizooSmsBundle:Default:verify, title: 'Verify Phone' }
    requirements:
        _method:  GET|POST
    
    
    
# CHARTER
ZizooBaseBundle_Dashboard_CharterDashboard:
    pattern:  /charter/account/dashboard
    defaults: { _controller: ZizooBaseBundle:Dashboard:indexCharter }
    requirements:
        _method:  GET

# CHARTER (shared dashboard action)
ZizooBaseBundle_Dashboard_CharterProfile:
    pattern:  /charter/account/dashboard/profile
    defaults: { _controller: ZizooBaseBundle:Dashboard:charter, other_controller: ZizooCharterBundle:Charter:profile, title: 'My Profile', tab: profile }
    requirements:
        _method:  GET|POST 

ZizooBaseBundle_Dashboard_CharterInbox:
    pattern:  /charter/account/dashboard/inbox
    defaults: { _controller: ZizooBaseBundle:Dashboard:charter, other_controller: ZizooMessageBundle:Message:inbox, title: 'My Inbox', tab: inbox }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_CharterViewThread:
    pattern:  /charter/account/dashboard/inbox/{threadId}
    defaults: { _controller: ZizooBaseBundle:Dashboard:charter, other_controller: FOSMessageBundle:Message:thread, view: 'charter', tab: inbox }
    requirements:
        _method:  GET|POST
        threadId: \d+
          
ZizooBaseBundle_Dashboard_CharterBookings:
    pattern:  /charter/account/dashboard/bookings
    defaults: { _controller: ZizooBaseBundle:Dashboard:charter, other_controller: ZizooCharterBundle:Charter:bookings, title: 'My Bookings', tab: bookings }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_CharterViewBooking:
    pattern:  /charter/account/dashboard/bookings/{id}
    defaults: { _controller: ZizooBaseBundle:Dashboard:charter, other_controller: ZizooCharterBundle:Charter:viewBooking, tab: bookings }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBaseBundle_Dashboard_CharterAcceptBooking:
    pattern:  /charter/account/dashboard/bookings/{id}/accept
    defaults: { _controller: ZizooBaseBundle:Dashboard:charter, other_controller: ZizooCharterBundle:Charter:acceptBookingRequest, tab: bookings }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBaseBundle_Dashboard_CharterDenyBooking:
    pattern:  /charter/account/dashboard/bookings/{id}/deny
    defaults: { _controller: ZizooBaseBundle:Dashboard:charter, other_controller: ZizooCharterBundle:Charter:denyBookingRequest, tab: bookings }
    requirements:
        _method:  GET|POST
        id: \d+ 
                        
ZizooBaseBundle_Dashboard_CharterPayments:
    pattern:  /charter/account/dashboard/payments
    defaults: { _controller: ZizooBaseBundle:Dashboard:charter, other_controller: ZizooCharterBundle:Charter:payments, title: 'My Payments', tab: payments }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_CharterPayoutSettings:
    pattern:  /charter/account/dashboard/payout-settings
    defaults: { _controller: ZizooBaseBundle:Dashboard:charter, other_controller: ZizooCharterBundle:Charter:payoutSettings, title: 'Payout Settings', tab: settings }
    requirements:
        _method:  GET|POST
       
ZizooBaseBundle_Dashboard_CharterBoats:
    pattern:  /charter/account/dashboard/boats/{page}
    defaults: { _controller: ZizooBaseBundle:Dashboard:charter, page: 1, other_controller: ZizooCharterBundle:Charter:boats, tab: boats }
    requirements:
        _method:  GET
        page: \d+
                

# CHARTER BOAT (shared dashboard action)
ZizooBaseBundle_Dashboard_CharterNewBoat:
    pattern:  /charter/account/dashboard/boat/new
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:new }
    requirements:
        _method:  GET|POST
        
ZizooBaseBundle_Dashboard_CharterEditBoat:
    pattern:  /charter/account/dashboard/boat/{id}/edit
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:edit }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBaseBundle_Dashboard_CharterEditDetailsBoat:
    pattern:  /charter/account/dashboard/boat/{id}/edit/details
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:editDetails }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBaseBundle_Dashboard_CharterEditPhotosBoat:
    pattern:  /charter/account/dashboard/boat/{id}/edit/photos
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:editPhotos }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBaseBundle_Dashboard_CharterEditPriceBoat:
    pattern:  /charter/account/dashboard/boat/{id}/edit/price
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:editPrice }
    requirements:
        _method:  GET|POST
        id: \d+
                 
ZizooBaseBundle_Dashboard_CharterDeleteBoat:
    pattern:  /charter/account/dashboard/boat/{id}/delete
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:delete }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBaseBundle_Dashboard_CharterActiveBoat:
    pattern:  /charter/account/dashboard/boat/{id}/active
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:active }
    requirements:
        _method:  GET|POST
        id: \d+