ZizooBaseBundle_homepage:
    pattern:  /
    defaults: { _controller: ZizooBaseBundle:Page:index }
    requirements:
        _method:  GET
        
ZizooBaseBundle_how:
    pattern:  /how/{what}
    defaults: { _controller: ZizooBaseBundle:Page:how, what: 'charter' }
    requirements:
        _method:  GET
        what: charter|holidayer|skipper
        
ZizooBaseBundle_about:
    pattern:  /about
    defaults: { _controller: ZizooBaseBundle:Page:about }
    requirements:
        _method:  GET
        
ZizooBaseBundle_terms:
    pattern:  /terms
    defaults: { _controller: ZizooBaseBundle:Page:terms }
    requirements:
        _method:  GET
        
ZizooBaseBundle_policies:
    pattern:  /policies
    defaults: { _controller: ZizooBaseBundle:Page:policies }
    requirements:
        _method:  GET
        
ZizooBaseBundle_feedback:
    pattern:  /feedback
    defaults: { _controller: ZizooBaseBundle:Page:feedback }
    requirements:
        _method:  GET|POST
        
ZizooBaseBundle_faq:
    pattern:  /faq
    defaults: { _controller: ZizooBaseBundle:Page:faq }
    requirements:
        _method:  GET
        
ZizooBaseBundle_login_page:
    pattern:  /login-page
    defaults: { _controller: ZizooBaseBundle:Page:login }
    requirements:
        _method:  GET|POST
        
ZizooBaseBundle_login_widget:
    pattern:  /login-widget
    defaults: { _controller: ZizooBaseBundle:Page:loginWidget }
    requirements:
        _method:  GET
                
                        
# USER                       
ZizooBaseBundle_Dashboard_UserDashboard:
    pattern:  /account/dashboard
    defaults: { _controller: ZizooBaseBundle:Dashboard:indexUser }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_Widget:
    pattern:  /dashboard-widget
    defaults: { _controller: ZizooBaseBundle:Dashboard:widget }
    requirements:
        _method:  GET

ZizooBaseBundle_Dashboard_Profile:
    pattern:  /account/dashboard/profile
    defaults: { _controller: ZizooBaseBundle:Dashboard:profile }
    requirements:
        _method:  GET|POST

ZizooBaseBundle_Dashboard_Skills:
    pattern:  /account/dashboard/skills
    defaults: { _controller: ZizooBaseBundle:Dashboard:skills }
    requirements:
        _method:  GET

ZizooBaseBundle_Dashboard_Trips:
    pattern:  /account/dashboard/trips
    defaults: { _controller: ZizooBaseBundle:Dashboard:trips }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_Inbox:
    pattern:  /account/dashboard/inbox
    defaults: { _controller: ZizooBaseBundle:Dashboard:inbox, message_controller: ZizooMessageBundle:Message:inbox }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_ViewThread:
    pattern:  /account/dashboard/inbox/{id}
    defaults: { _controller: ZizooBaseBundle:Dashboard:viewThread, message_controller: FOSMessageBundle:Message:thread }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBaseBundle_Dashboard_AccountSettings:
    pattern:  /account/dashboard/settings
    defaults: { _controller: ZizooBaseBundle:Dashboard:accountSettings }
    requirements:
        _method:  GET|POST
   
ZizooBaseBundle_Dashboard_VerifyFacebook:
    pattern:  /account/dashboard/verify-facebook
    defaults: { _controller: ZizooBaseBundle:Dashboard:verifyFacebook }
    requirements:
        _method:  GET|POST
        
ZizooBaseBundle_Dashboard_UnverifyFacebook:
    pattern:  /account/dashboard/unverify-facebook
    defaults: { _controller: ZizooBaseBundle:Dashboard:unverifyFacebook }
    requirements:
        _method:  GET|POST
    
    
    
# CHARTER
ZizooBaseBundle_Dashboard_CharterDashboard:
    pattern:  /charter/account/dashboard
    defaults: { _controller: ZizooBaseBundle:Dashboard:indexCharter }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_CharterProfile:
    pattern:  /charter/account/dashboard/profile
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterProfile }
    requirements:
        _method:  GET|POST    
        
ZizooBaseBundle_Dashboard_CharterInbox:
    pattern:  /charter/account/dashboard/inbox
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterInbox, message_controller: ZizooMessageBundle:Message:inbox }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_CharterViewThread:
    pattern:  /charter/account/dashboard/inbox/{id}
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterViewThread, message_controller: FOSMessageBundle:Message:thread }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBaseBundle_Dashboard_CharterBookings:
    pattern:  /charter/account/dashboard/bookings
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBookings }
    requirements:
        _method:  GET
                        
ZizooBaseBundle_Dashboard_CharterPayments:
    pattern:  /charter/account/dashboard/payments
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterPayments }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_CharterPayoutSettings:
    pattern:  /charter/account/dashboard/payout-settings
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterPayoutSettings }
    requirements:
        _method:  GET|POST
       
        

# CHARTER BOATS
ZizooBaseBundle_Dashboard_CharterBoats:
    pattern:  /charter/account/dashboard/boats/{page}
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoats, page: 1 }
    requirements:
        _method:  GET
        page: \d+
        

ZizooBaseBundle_Dashboard_CharterNewBoat:
    pattern:  /charter/account/dashboard/boat/new
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:new }
    requirements:
        _method:  GET|POST
        
ZizooBaseBundle_Dashboard_CharterEditBoat:
    pattern:  /charter/account/dashboard/boat/{id}/edit
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:edit }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBaseBundle_Dashboard_CharterEditDetailsBoat:
    pattern:  /charter/account/dashboard/boat/{id}/edit/details
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:editDetails }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBaseBundle_Dashboard_CharterEditPhotosBoat:
    pattern:  /charter/account/dashboard/boat/{id}/edit/photos
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:editPhotos }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBaseBundle_Dashboard_CharterEditPriceBoat:
    pattern:  /charter/account/dashboard/boat/{id}/edit/price
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:editPrice }
    requirements:
        _method:  GET|POST
        id: \d+
                 
ZizooBaseBundle_Dashboard_CharterDeleteBoat:
    pattern:  /charter/account/dashboard/boat/{id}/delete
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:delete }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooBaseBundle_Dashboard_CharterActiveBoat:
    pattern:  /charter/account/dashboard/boat/{id}/active
    defaults: { _controller: ZizooBaseBundle:Dashboard:charterBoat, boat_controller: ZizooBoatBundle:Boat:active }
    requirements:
        _method:  GET|POST
        id: \d+