ZizooBaseBundle_homepage:
    pattern:  /
    defaults: { _controller: ZizooBaseBundle:Page:index }
    requirements:
        _method:  GET
        
ZizooBaseBundle_how:
    pattern:  /how
    defaults: { _controller: ZizooBaseBundle:Page:how }
    requirements:
        _method:  GET
        
ZizooBaseBundle_about:
    pattern:  /about
    defaults: { _controller: ZizooBaseBundle:Page:about }
    requirements:
        _method:  GET
        
ZizooBaseBundle_terms:
    pattern:  /terms
    defaults: { _controller: ZizooBaseBundle:Page:terms }
    requirements:
        _method:  GET
        
ZizooBaseBundle_policies:
    pattern:  /policies
    defaults: { _controller: ZizooBaseBundle:Page:policies }
    requirements:
        _method:  GET
        
ZizooBaseBundle_feedback:
    pattern:  /feedback
    defaults: { _controller: ZizooBaseBundle:Page:feedback }
    requirements:
        _method:  GET|POST
        
ZizooBaseBundle_faq:
    pattern:  /faq
    defaults: { _controller: ZizooBaseBundle:Page:faq }
    requirements:
        _method:  GET
        
ZizooBaseBundle_login_widget:
    pattern:  /login-widget
    defaults: { _controller: ZizooBaseBundle:Page:loginWidget }
    requirements:
        _method:  GET
        
ZizooBaseBundle_dashboard:
    pattern:  /account/dashboard
    defaults: { _controller: ZizooBaseBundle:Dashboard:index }
    requirements:
        _method:  GET
        
ZizooBaseBundle_dashboard_user_widget:
    pattern:  /dashboard-user-widget
    defaults: { _controller: ZizooBaseBundle:Dashboard:userWidget }
    requirements:
        _method:  GET
        
ZizooBaseBundle_dashboard_profile:
    pattern:  /account/profile
    defaults: { _controller: ZizooBaseBundle:Dashboard:profile }
    requirements:
        _method:  GET
        
ZizooBaseBundle_dashboard_boats:
    pattern:  /account/boats
    defaults: { _controller: ZizooBaseBundle:Dashboard:boats }
    requirements:
        _method:  GET
        
ZizooBaseBundle_dashboard_boat_new:
    pattern:  /account/boat/new
    defaults: { _controller: ZizooBaseBundle:Dashboard:boatNew }
    requirements:
        _method:  GET
        
ZizooBaseBundle_dashboard_boat_edit:
    pattern:  /account/boat/{id}/edit
    defaults: { _controller: ZizooBaseBundle:Dashboard:boatEdit }
    requirements:
        _method:  GET
        id: \d+
        
ZizooBaseBundle_dashboard_boat_photos:
    pattern:  /account/boat/photos
    defaults: { _controller: ZizooBaseBundle:Dashboard:boatPhotos }
    requirements:
        _method:  POST
        
ZizooBaseBundle_dashboard_boat_price:
    pattern:  /account/boat/{id}/price
    defaults: { _controller: ZizooBaseBundle:Dashboard:boatPrice }
    requirements:
        _method:  GET
        
ZizooBaseBundle_dashboard_skills:
    pattern:  /account/skills
    defaults: { _controller: ZizooBaseBundle:Dashboard:skills }
    requirements:
        _method:  GET
        
ZizooBaseBundle_dashboard_trips:
    pattern:  /account/trips
    defaults: { _controller: ZizooBaseBundle:Dashboard:trips }
    requirements:
        _method:  GET
        
ZizooBaseBundle_dashboard_account:
    pattern:  /account/settings
    defaults: { _controller: ZizooBaseBundle:Dashboard:settings }
    requirements:
        _method:  GET|POST