ZizooBaseBundle_homepage:
    pattern:  /
    defaults: { _controller: ZizooBaseBundle:Page:index }
    requirements:
        _method:  GET
        
ZizooBaseBundle_about:
    pattern:  /about
    defaults: { _controller: ZizooBaseBundle:Page:about }
    requirements:
        _method:  GET
        
        
ZizooBaseBundle_dashboard:
    pattern:  /dashboard/{userId}
    defaults: { _controller: ZizooBaseBundle:Dashboard:index }
    requirements:
        _method:  GET
        userId: \d+