ZizooBaseBundle_homepage:
    pattern:  /
    defaults: { _controller: ZizooBaseBundle:Page:index }
    requirements:
        _method:  GET
        
ZizooBaseBundle_how:
    pattern:  /how
    defaults: { _controller: ZizooBaseBundle:Page:how }
    requirements:
        _method:  GET
        
ZizooBaseBundle_about:
    pattern:  /about
    defaults: { _controller: ZizooBaseBundle:Page:about }
    requirements:
        _method:  GET
        
ZizooBaseBundle_terms:
    pattern:  /terms
    defaults: { _controller: ZizooBaseBundle:Page:terms }
    requirements:
        _method:  GET
        
ZizooBaseBundle_policies:
    pattern:  /policies
    defaults: { _controller: ZizooBaseBundle:Page:policies }
    requirements:
        _method:  GET
        
ZizooBaseBundle_feedback:
    pattern:  /feedback
    defaults: { _controller: ZizooBaseBundle:Page:feedback }
    requirements:
        _method:  GET|POST
        
ZizooBaseBundle_faq:
    pattern:  /faq
    defaults: { _controller: ZizooBaseBundle:Page:faq }
    requirements:
        _method:  GET
        
ZizooBaseBundle_login_widget:
    pattern:  /login-widget
    defaults: { _controller: ZizooBaseBundle:Page:loginWidget }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard:
    pattern:  /account/dashboard
    defaults: { _controller: ZizooBaseBundle:Dashboard:index }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_Widget:
    pattern:  /dashboard-widget
    defaults: { _controller: ZizooBaseBundle:Dashboard:widget }
    requirements:
        _method:  GET
       
ZizooBaseBundle_Dashboard_Skills:
    pattern:  /account/skills
    defaults: { _controller: ZizooBaseBundle:Dashboard:skills }
    requirements:
        _method:  GET
        
ZizooBaseBundle_Dashboard_Trips:
    pattern:  /account/trips
    defaults: { _controller: ZizooBaseBundle:Dashboard:trips }
    requirements:
        _method:  GET
        
        
test:
    pattern:  /test1
    defaults: { _controller: ZizooBaseBundle:Page:test1 }
    requirements:
        _method:  GET

test2:
    pattern:  /test2
    defaults: { _controller: ZizooBaseBundle:Page:test2 }
    requirements:
        _method:  GET
       