parameters:
#    zizoo_base.example.class: Zizoo\BaseBundle\Example

services:
    twigdate.listener.request:
        class: Zizoo\BaseBundle\Service\TwigDateRequestListener
        arguments: ["@twig"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
#    zizoo_base.example:
#        class: %zizoo_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
