parameters:
#    zizoo_base.example.class: Zizoo\BaseBundle\Example

services:
    twigdate.listener.request:
        class: Zizoo\BaseBundle\Service\TwigDateRequestListener
        arguments: ["@twig"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
#    zizoo_base.example:
#        class: %zizoo_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    zizoo_base.twig.picture_extension:
        class: Zizoo\BaseBundle\Twig\PictureExtension
        tags:
            - { name: twig.extension }
            
    zizoo_base.twig.base_extension:
        class: Zizoo\BaseBundle\Twig\BaseExtension
        tags:
            - { name: twig.extension }
            
    zizoo_base.number_nullable_type:
        class:  Zizoo\BaseBundle\Form\Type\NumberNullableType
        tags:
            - { name: form.type, alias: zizoo_number_nullable }
            
    zizoo_base.terms_type:
        class:  Zizoo\BaseBundle\Form\Type\TermsType
        tags:
            - { name: form.type, alias: zizoo_terms }
            
    zizoo_base.terms_type_extension:
        class:  Zizoo\BaseBundle\Form\Extension\TermsTypeExtension
        tags:
            - { name: form.type_extension, alias: zizoo_terms }