parameters:
#    zizoo_base.example.class: Zizoo\BaseBundle\Example

services:
    zizoo_base.twig.picture_extension:
        class: Zizoo\BaseBundle\Twig\PictureExtension
        tags:
            - { name: twig.extension }
