ZizooCrewBundle_Skills_Add:
    pattern:  /account/skills/add
    defaults: { _controller: "ZizooCrewBundle:Skills:add" }
    requirements:
      _method:  GET|POST

ZizooCrewBundle_Skills_SetLicense:
    pattern:  /account/skills/set
    defaults: { _controller: "ZizooCrewBundle:Skills:setLicense" }
    requirements:
      _method:  POST

ZizooCrewBundle_Skills_GetLicense:
    pattern:  /account/skills/license
    defaults: { _controller: "ZizooCrewBundle:Skills:getLicense" }
    requirements:
      _method:  GET