parameters:
#    zizoo_crew.example.class: Zizoo\SkipperBundle\Example

services:
#    zizoo_crew.example:
#        class: %zizoo_crew.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
