parameters:
#    zizoo_crew.example.class: Zizoo\SkipperBundle\Example

services:
    zizoo_crew.license_type:
        class:  Zizoo\CrewBundle\Form\LicenseType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: zizoo_license }
