ZizooReservationBundle_view:
    pattern:  /charter/account/reservation/{id}
    defaults: { _controller: ZizooReservationBundle:Reservation:viewReservation }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooReservationBundle_accept:
    pattern:  /charter/account/reservation/{id}/accept
    defaults: { _controller: ZizooReservationBundle:Reservation:acceptReservationRequest }
    requirements:
        _method:  GET|POST
        id: \d+
        
ZizooReservationBundle_deny:
    pattern:  /charter/account/reservation/{id}/deny
    defaults: { _controller: ZizooReservationBundle:Reservation:denyReservationRequest }
    requirements:
        _method:  GET|POST
        id: \d+