parameters:
    zizoo_reservation.reservation_request_response_hours: 48
    zizoo_reservation.min_reservation_days_in_advance: 7
#    zizoo_reservation.example.class: Zizoo\ReservationBundle\Example

services:
    zizoo_reservation_reservation_agent:
        class:  Zizoo\ReservationBundle\Service\ReservationAgent
        arguments: 
            entityManager:  "@doctrine.orm.entity_manager"
            messenger:      "@messenger"
            container:      "@service_container"
            
    zizoo_reservation_reservation_listener:
        class: Zizoo\ReservationBundle\EventListener\ReservationListener
        arguments:
            container:      "@service_container"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            
    zizoo_booking.twig.reservation_extension:
        class: Zizoo\ReservationBundle\Twig\ReservationExtension
        arguments:
            container:      "@service_container"
        tags:
            - { name: twig.extension }

    # FORM TYPES
    zizoo_reservation.deny_reservation_type:
        class:  Zizoo\ReservationBundle\Form\Type\DenyReservationType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: zizoo_reservation_deny }
            
    # VALIDATORS