zizoo_address_unique_locations:
    pattern:  /unique_locations/{current}
    defaults: { _controller: ZizooAddressBundle:Address:uniqueLocations, current: '-1', _format: json }
    requirements: { _format: (xml|json), _method: GET }

zizoo_address_locations:
    pattern:  /locations/{page}/{search}
    defaults: { _controller: ZizooAddressBundle:Address:locations, page: '1', search: '-1'}
