parameters:
#    zizoo_address.example.class: Zizoo\AddressBundle\Example

services:
    
    zizoo_address.unique_locations_type:
        class:  Zizoo\AddressBundle\Form\Type\UniqueLocationsType
        tags:
            - { name: form.type, alias: zizoo_unique_locations }
            
    zizoo_address.filter_boat_type:
        class:  Zizoo\AddressBundle\Form\Type\FilterBoatType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: zizoo_boat_filter }
    
    zizoo_address.search_boat_type:
        class:  Zizoo\AddressBundle\Form\Type\SearchBoatType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: zizoo_boat_search }
            
    
#    zizoo_address.example:
#        class: %zizoo_address.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]