parameters:
#    zizoo_billing.example.class: Zizoo\BillingBundle\Example

services:
#    zizoo_billing.example:
#        class: %zizoo_billing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
