parameters:
#    zizoo_event.example.class: Zizoo\EventBundle\Example

services:
#    zizoo_event.example:
#        class: %zizoo_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
