<?php

namespace Zizoo\SmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileVerifyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileVerifyRepository extends EntityRepository
{
    public function getProfileAndPhone($profile, $phone)
    {
        $qb = $this->createQueryBuilder('booking')
            ->leftJoin('booking.reservation', 'reservation')
            ->leftJoin('reservation.boat', 'boat')
            ->leftJoin('reservation.guest', 'guest')
            ->leftJoin('boat.charter', 'charter')
            ->select('booking')
            ->where('charter = :charter')
            ->setParameter('charter', $charter);

        if ($status){
            $qb->andWhere('booking.status = :status')
                ->setParameter('status', $status);
        }

        return $qb->getQuery()
            ->getResult();
    }
}
