<?php

namespace Zizoo\AddressBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
    
    public function allCountriesAsSelect(){
        $qb = $this->createQueryBuilder('country')
                    ->select('country.iso as countryISO, country.printableName as countryName')
                    ->addOrderBy('country.printableName', 'asc');

        $selectCountries = array();
        $countries = $qb->getQuery()->getResult();
        foreach ($countries as $country){
            $selectCountries[$country['countryISO']] = $country['countryName'];
        }
        return $selectCountries;
    }
    
}
