<?php

namespace Zizoo\AddressBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository
{
    public function getAllLanguages(){
        $qb = $this->createQueryBuilder('language')
            ->select('name');

        return $qb->getQuery()
            ->getResult();
    }
}
