<?php

namespace Zizoo\AddressBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarinaRepository extends EntityRepository
{
    public function getAllMarinas(){
        $qb = $this->createQueryBuilder('marina')
                   ->select('marina');

        return $qb->getQuery()
                  ->getResult();
    }
    
}
