parameters:
#    zizoo_charter.example.class: Zizoo\CharterBundle\Example

services:
      zizoo_charter_charter_service:
              class:  Zizoo\CharterBundle\Service\CharterService
              arguments: 
                  entityManager:  "@doctrine.orm.entity_manager"
                  container:      "@service_container" 
                  
      zizoo_charter.charter_registration_type:
        class:  Zizoo\CharterBundle\Form\Type\CharterRegistrationType
        tags:
            - { name: form.type, alias: zizoo_charter_registration_type }