# src/Zizoo/CharterBundle/Resources/config/validation.yml
Zizoo\CharterBundle\Entity\Charter:
    properties:
        charterName:
            - NotBlank: { message: zizoo_charter.error.charter_name_not_blank, groups: [registration] }
            
        phone:
            - NotBlank: { message: zizoo_charter.error.charter_phone_not_blank, groups: [registration] }
            
Zizoo\AddressBundle\Entity\CharterAddress:
    properties:
        addressLine1:
            - NotBlank: { message: zizoo_charter.error.charter_address_street_not_blank, groups: [registration] }

        postcode:
            - NotBlank: { message: zizoo_charter.error.charter_address_postcode_not_blank, groups: [registration] }
            
        locality:
            - NotBlank: { message: zizoo_charter.error.charter_address_locality_not_blank, groups: [registration] }
            
        country:
            - NotNull: { message: zizoo_charter.error.charter_address_country_not_null, groups: [registration] }