<?php

namespace Zizoo\EventBundle\Entity;

use Zizoo\EventBundle\Entity\Event;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    
    public function getPossibleRunEvents(\DateTime $now, $retries)
    {
        
        $qb = $this->createQueryBuilder('event')
                    ->select('event')
                    ->where('event.status = :new_status')
                    ->orWhere('event.status = :complete_status AND event.retry < :retries')
                    ->setParameter('new_status', Event::STATUS_NEW)
                    ->setParameter('complete_status', Event::STATUS_COMPLETE)
                    ->setParameter('retries', $retries)
                    ->setMaxResults(100);
        
        return $qb->getQuery()
                  ->getResult();
    }

    
}
