<?php

namespace Zizoo\CharterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharterRepository extends EntityRepository
{
    public function getCharterEarnings(Charter $charter)
    {
        $qb = $this->createQueryBuilder('boat')
            ->leftJoin('boat.charter', 'charter')
            ->select('boat, charter')
            ->where('charter = :charter')
            ->andWhere('boat.deleted IS NULL')
            ->setParameter('charter', $charter);

        return $qb->getQuery()
            ->getResult();
    }
}
