<?php

namespace Zizoo\CharterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharterRepository extends EntityRepository
{
}
