<?php

namespace Zizoo\Bundle\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * RegionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{
    const CACHE_TTL = 86400;

    /**
     * @param $parent
     *
     * @return array
     */
    public function findByParentFull(Region $parent)
    {
        $qb = $this->createQueryBuilder('region')
            ->select('region','regionPagePart')
            ->leftJoin('region.regionPagePart', 'regionPagePart')
            ->where('region.parent = :parent')
            ->setParameter('parent', $parent)
        ;

        return $qb->getQuery()
            ->useResultCache(true, self::CACHE_TTL)
            ->getResult();
    }
}
